lib: [
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/META"
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/bin/pesy-modules/SiteBinPesyModules.a" {"bin/pesy-modules/SiteBinPesyModules.a"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/bin/pesy-modules/SiteBinPesyModules.cma" {"bin/pesy-modules/SiteBinPesyModules.cma"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/bin/pesy-modules/SiteBinPesyModules.cmxa" {"bin/pesy-modules/SiteBinPesyModules.cmxa"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/bin/pesy-modules/SiteBinPesyModules.cmxs" {"bin/pesy-modules/SiteBinPesyModules.cmxs"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/bin/pesy-modules/SiteBinPesyModules.re" {"bin/pesy-modules/SiteBinPesyModules.re"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/bin/pesy-modules/siteBinPesyModules.cmi" {"bin/pesy-modules/siteBinPesyModules.cmi"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/bin/pesy-modules/siteBinPesyModules.cmt" {"bin/pesy-modules/siteBinPesyModules.cmt"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/bin/pesy-modules/siteBinPesyModules.cmx" {"bin/pesy-modules/siteBinPesyModules.cmx"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/dune-package"
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/lib/SiteLib.a" {"lib/SiteLib.a"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/lib/SiteLib.cma" {"lib/SiteLib.cma"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/lib/SiteLib.cmxa" {"lib/SiteLib.cmxa"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/lib/SiteLib.cmxs" {"lib/SiteLib.cmxs"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/lib/Util.re" {"lib/Util.re"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/lib/Util.rei" {"lib/Util.rei"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/lib/siteLib.cmi" {"lib/siteLib.cmi"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/lib/siteLib.cmt" {"lib/siteLib.cmt"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/lib/siteLib.cmx" {"lib/siteLib.cmx"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/lib/siteLib.ml" {"lib/siteLib.ml"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/lib/siteLib__Util.cmi" {"lib/siteLib__Util.cmi"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/lib/siteLib__Util.cmt" {"lib/siteLib__Util.cmt"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/lib/siteLib__Util.cmti" {"lib/siteLib__Util.cmti"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/lib/siteLib__Util.cmx" {"lib/siteLib__Util.cmx"}
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/lib/site/opam"
]
bin: [
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/bin/SiteApp"
]
doc: [
  "/home/rohitkg98/projects/site/_esy/default/store/b/site-0fa0e17e/install/default/doc/site/README.md"
]
